@API_CONSULTATION_HostAddress = http://localhost:5261

GET {{API_CONSULTATION_HostAddress}}/todos/
Accept: application/json

###

GET {{API_CONSULTATION_HostAddress}}/todos/1
Accept: application/json

###
